on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'phpstan.neon'
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'phpstan.neon'
    branches:
      - main

name: static analysis

jobs:
  phpstan:
    uses: zorachka/actions/.github/workflows/phpstan.yml@main
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
