on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'phpunit.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'phpunit.xml'
    branches:
      - main

name: test

jobs:
  phpunit:
    uses: zorachka/actions/.github/workflows/phpunit.yml@main
    with:
      # coverage: pcov / coverage: xdebug / coverage: xdebug2 / coverage: none
      extensions: apcu
      # ini-values: date.timezone='UTC'
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
      tools: composer:v2
